version: '3.9'
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env


  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server